substitutions:
  _DEPLOY_REGION: europe-north1
  _SERVICE_ACCOUNT: onoff-updater-sa@home-automation-18714.iam.gserviceaccount.com

steps:
  # Check out the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: [ 'clone', 'https://github.com/tomas-fpcs/onoff-updater.git' ]
    dir: '/workspace'

  # Set up JDK 17 and build the project with Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'clean', 'install' ]
    dir: 'onoff-updater'

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/onoff-updater', '.' ]
    dir: '/workspace/onoff-updater'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/onoff-updater' ]

  # Deploy the image as a Cloud Run Job
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - jobs
      - deploy
      - onoff-updater-job  # Cloud Run Job name
      - --image=gcr.io/$PROJECT_ID/onoff-updater
      - --region=$_DEPLOY_REGION
      - --task-timeout=900s # Max execution time (15 min)
      - --set-env-vars=SPRING_PROFILES_ACTIVE=prod
      - --set-env-vars=MONGODB_CONNECTION_STRING=$_MONGODB_CONNECTION_STRING
      - --set-env-vars=GOOGLE_CLOUD_PROJECT=$_GOOGLE_CLOUD_PROJECT
      - --set-env-vars=DEPLOY_REGION=$_DEPLOY_REGION
      - --set-env-vars=LOGGING_LEVEL_SE_FPCS=TRACE

  # Execute the Cloud Run Job immediately after deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - jobs
      - execute
      - onoff-updater-job
      - --region=$_DEPLOY_REGION

  # Create or update the Cloud Scheduler job to run hourly
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - scheduler
      - jobs
      - describe
      - hourly-onoff-updater
      - --location=$_DEPLOY_REGION
    id: check-job
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - scheduler
      - jobs
      - update
      - http
      - hourly-onoff-updater
      - --schedule="0 * * * *"
      - --uri="https://$_DEPLOY_REGION-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/onoff-updater-job:run"
      - --http-method=POST
      - --oauth-service-account-email=$_SERVICE_ACCOUNT
      - --location=$_DEPLOY_REGION
    id: update-job
    waitFor: ['check-job']
    allowFailure: true

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - scheduler
      - jobs
      - create
      - http
      - hourly-onoff-updater
      - --schedule="0 * * * *"
      - --uri="https://$_DEPLOY_REGION-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/onoff-updater-job:run"
      - --http-method=POST
      - --oauth-service-account-email=$_SERVICE_ACCOUNT
      - --location=$_DEPLOY_REGION
    id: create-job
    waitFor: ['update-job']
    allowFailure: true

images:
  - 'gcr.io/$PROJECT_ID/onoff-updater'

options:
  logging: CLOUD_LOGGING_ONLY
