spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING}
      database: ONOFF
    rest:
      enabled: false

logging:
  level:
    root: INFO
    se.fpcs: INFO